"""The one exposed port: what it advertises, and who it lets in (§4.6, §10.5)."""

from pathlib import Path

import pytest
from asyncua import Client, Server, ua
from asyncua.crypto import security_policies
from simulator.config import Settings
from simulator.pki import PARTIES, Party, gen_party
from simulator.server import build_server

GATEWAY = PARTIES["edge-gateway"]

# A fourth identity, minted into a root of its own. gen_party always publishes to
# <root>/trusted/certs/ -- that is what makes the plant and the gateway trust each
# other without a manual step -- so the only way to hold a certificate the server has
# never been given is to publish it into a trust store the server never reads.
STRANGER = Party(
    name="stranger",
    app_uri="urn:machine-agent:test:stranger",
    dns_names=("stranger",),
    client_auth=True,
    subject={"organizationName": "machine-agent", "countryName": "DE"},
)

# 127.0.0.1, not `line-simulator`, even though the real boundary only ever uses the
# latter: the name resolves on a developer machine and not on a CI runner, and a unit
# test that silently depends on that is a test that passes here and fails there. The
# name itself is pinned against the certificate and the Compose service in
# test_compose_invariants.py, where checking it costs no DNS.
#
# Port 0, so the OS assigns one. Three sessions run `make check-python` on every commit
# and a fixed port here is a collision waiting for the day two of them overlap; the port
# asyncua actually bound is read back with `dial()` below.
LISTEN = "opc.tcp://127.0.0.1:0/plant"


@pytest.fixture(scope="module")
def pki(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Both real parties, minted fresh rather than read from the repository's `pki/`
    -- that directory is generated by the pki-init container and is absent on a clean
    checkout, which would make these tests pass or fail on whether someone had run
    Compose."""
    root = tmp_path_factory.mktemp("pki")
    for party in PARTIES.values():
        gen_party(party, root)
    return root


@pytest.fixture(scope="module")
def stranger_pki(tmp_path_factory: pytest.TempPathFactory) -> Path:
    root = tmp_path_factory.mktemp("stranger-pki")
    gen_party(STRANGER, root)
    return root


def dial(server: Server) -> str:
    """The URL a client must use to reach `server`, once it is started.

    asyncua resolves a port-0 endpoint into BinaryServer.port when it binds; the
    advertised endpoint still reads `:0`, which does not matter because the server
    echoes back the netloc the client sent in GetEndpoints (see server.py).
    """
    assert server.bserver is not None, "the server has no port until it is started"
    return f"opc.tcp://127.0.0.1:{server.bserver.port}/plant"


def _certs(root: Path, name: str) -> tuple[str, str]:
    return (
        str(root / name / "certs" / f"{name}.der"),
        str(root / name / "private" / f"{name}.pem"),
    )


@pytest.mark.asyncio
async def test_server_advertises_only_sign_no_unsecured_endpoint(pki: Path) -> None:
    """§4.6: SecurityMode Sign. §10.5 rules out SignAndEncrypt for M1. An open
    endpoint would make the boundary narrow but unauthenticated."""
    settings = Settings(endpoint_url=LISTEN, pki_root=str(pki))
    server, _ = await build_server(settings)
    async with server:
        endpoints = await server.get_endpoints()

    assert endpoints
    assert {e.SecurityMode for e in endpoints} == {ua.MessageSecurityMode.Sign}
    assert all("Basic256Sha256" in e.SecurityPolicyUri for e in endpoints)


@pytest.mark.asyncio
async def test_an_untrusted_client_is_rejected(pki: Path, stranger_pki: Path) -> None:
    """Mutual trust means the server refuses a certificate it has never been given.

    The stranger presents an ApplicationUri that genuinely is in its own certificate,
    so the only thing wrong with the handshake is that nobody trusts it -- otherwise
    this passes on BadCertificateUriInvalid and proves nothing about the trust store.
    """
    settings = Settings(endpoint_url=LISTEN, pki_root=str(pki))
    server, _ = await build_server(settings)
    cert, key = _certs(stranger_pki, STRANGER.name)
    async with server:
        client = Client(dial(server))
        client.application_uri = STRANGER.app_uri
        await client.set_security(
            security_policies.SecurityPolicyBasic256Sha256,
            certificate=cert,
            private_key=key,
            server_certificate=_certs(pki, "line-simulator")[0],
            mode=ua.MessageSecurityMode.Sign,
        )
        with pytest.raises(ua.UaStatusCodeError) as excinfo:
            await client.connect()

    assert excinfo.value.code == ua.StatusCodes.BadCertificateUntrusted


@pytest.mark.asyncio
async def test_the_trusted_gateway_certificate_connects_and_browses(pki: Path) -> None:
    """The gateway discovers the line by browsing, so a session that cannot browse is
    not a working boundary even when the handshake succeeded (§4.1)."""
    settings = Settings(endpoint_url=LISTEN, pki_root=str(pki))
    server, space = await build_server(settings)
    cert, key = _certs(pki, GATEWAY.name)
    async with server:
        client = Client(dial(server))
        client.application_uri = GATEWAY.app_uri
        await client.set_security(
            security_policies.SecurityPolicyBasic256Sha256,
            certificate=cert,
            private_key=key,
            server_certificate=_certs(pki, "line-simulator")[0],
            mode=ua.MessageSecurityMode.Sign,
        )
        async with client:
            node = client.get_node(space.s3.nodeid)
            names = {
                (await c.read_browse_name()).Name for c in await node.get_children()
            }

    assert {"TaktTime", "PartCount"} <= names


@pytest.mark.asyncio
async def test_an_unsecured_client_cannot_reach_the_address_space(pki: Path) -> None:
    """The complement of the endpoint listing above: no open endpoint means a client
    that offers no certificate at all gets no session, not merely a less-preferred one."""
    settings = Settings(endpoint_url=LISTEN, pki_root=str(pki))
    server, _ = await build_server(settings)
    async with server:
        client = Client(dial(server))
        with pytest.raises(ua.UaError):
            await client.connect()
